# Generated by Django 4.0.6 on 2022-07-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('factory_code', models.CharField(max_length=20, verbose_name='Reporting Factory Code')),
            ],
            options={
                'verbose_name_plural': 'Factories',
            },
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_to_business', models.CharField(choices=[('JTI Employee', 'JTI Employee (permanent, temporary/seasonal)'), ('Outsourced', 'Outsourced personnel /Supervised employee (JTI direct supervision)'), ('Contractor', 'Contractor'), ('Public', 'Member of public (no direct contractual relationship between JTI and injured person)')], max_length=100, verbose_name='Relation to Businesss')),
                ('severity', models.CharField(choices=[('Fatality', 'Fatality'), ('LTI', '(LTI) Lost time injury'), ('RWC', '(RWC) Restricted work case'), ('MTC', '(MTC) Medical treatment case'), ('First aid', 'First aid')], max_length=100, verbose_name='Severity')),
                ('consequence', models.CharField(choices=[('1', 'Respiratory disease (eg Green tobacco sickness, Asthma, Chronic pulmonary disease)'), ('2', 'Skin disease (eg Dermatitis, Urticaria)'), ('3', 'Musculoskeletal disorder (eg Carpal tunnel syndrome, Hernia, Back pains)'), ('4', 'Hearing loss/impairment'), ('5', 'Mental and behavioral disorder (eg Burnout, Post-traumatic stress, Anxiety)'), ('6', 'Other (please specify)')], max_length=100, verbose_name='Consequence')),
                ('immediate_cause', models.CharField(choices=[('1', 'Exposure to physical agents (Noise, Vibration, Ionizing radiations, Heat radiation, Ultraviolet radiation, Extreme temperature, Intense light etc.)'), ('2', 'Exposure to chemical agents (Allergic provoking agents, Irritants agents from work activities such as organic solvents, ammonia, Cadmium, phosphorus, lead and their compounds….)'), ('3', 'Exposure to biological agents and infectious or parasitic diseases (Viruses, Bacteria, Fungi etc.)'), ('4', 'Long term exposure to repetitive movements or long hours in a static position'), ('5', 'Long term exposure to heavy workload'), ('6', 'Other (please specify)')], max_length=100, verbose_name='Immediate Cause - Occ. Health')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=100, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_to_business', models.CharField(choices=[('JTI Employee', 'JTI Employee (permanent, temporary/seasonal)'), ('Outsourced', 'Outsourced personnel /Supervised employee (JTI direct supervision)'), ('Contractor', 'Contractor'), ('Public', 'Member of public (no direct contractual relationship between JTI and injured person)')], max_length=100, verbose_name='Relation to Businesss')),
                ('severity', models.CharField(max_length=100, verbose_name='Severity')),
                ('immediate_cause', models.CharField(choices=[('1', 'Exposure to physical agents (Noise, Vibration, Ionizing radiations, Heat radiation, Ultraviolet radiation, Extreme temperature, Intense light etc.)'), ('2', 'Exposure to chemical agents (Allergic provoking agents, Irritants agents from work activities such as organic solvents, ammonia, Cadmium, phosphorus, lead and their compounds….)'), ('3', 'Exposure to biological agents and infectious or parasitic diseases (Viruses, Bacteria, Fungi etc.)'), ('4', 'Long term exposure to repetitive movements or long hours in a static position'), ('5', 'Long term exposure to heavy workload'), ('6', 'Other (please specify)')], max_length=100, verbose_name='Immediate Cause - Safety')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='First name')),
                ('surname', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='Password')),
                ('hash', models.CharField(max_length=100, verbose_name='Password hash')),
            ],
        ),
        migrations.CreateModel(
            name='HS_incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_activity', models.CharField(choices=[('Manufacturing', 'Manufacturing Operations'), ('Leaf', 'Leaf Origins'), ('Market', 'Market'), ('R&D', 'R&D'), ('GBS', 'GBS'), ('CSS', 'CSS')], max_length=50, verbose_name='Business Activity')),
                ('incident_classification', models.CharField(choices=[(1, 'Safety'), (2, 'Occupational Health')], max_length=50, verbose_name='Incident Classification')),
                ('work_related', models.BooleanField(verbose_name='Work related')),
                ('external_authority_notification', models.BooleanField(verbose_name='Ext. Auth. notification?')),
                ('incident_description', models.TextField(verbose_name='Incident Description')),
                ('incident_location', models.CharField(choices=[('Onsite', 'ON-site'), ('Offsite', 'OFF-site')], max_length=50, verbose_name='Incident Location')),
                ('lat', models.FloatField(null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(null=True, verbose_name='Longitude')),
                ('date_occured', models.DateField(verbose_name='Date Occurred')),
                ('date_reported', models.DateField(verbose_name='Date Reported to Local H&S')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('simp_id', models.IntegerField(null=True, verbose_name='SIMP id')),
                ('date_created', models.DateField(verbose_name='Date created')),
                ('illness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hs_incident', to='hs_incidents.illness', verbose_name='Illness')),
                ('injury', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hs_incident', to='hs_incidents.injury', verbose_name='Injuries')),
                ('jti_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hs_incidents', to='hs_incidents.site', verbose_name='JTI site')),
                ('reporting_factory_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hs_incidents', to='hs_incidents.factory', verbose_name='Reporting Factory Code')),
            ],
        ),
    ]
