# Generated by Django 4.0.6 on 2022-08-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hs_incident',
            name='reporting_factory_code',
        ),
        migrations.AlterField(
            model_name='hs_incident',
            name='jti_site',
            field=models.CharField(choices=[('1419', '🏠 Babol, Iran: Office cat. B'), ('934', '📦Zanjan, Iran: NTM WH cat. C Machinery WH'), ('933', '🏠Tehran, Iran: Office cat. B (South Tehran)'), ('932', '🏠Tehran, Iran: Office cat. B (West Tehran)'), ('931', '🏠Karaj, Iran: Office cat. B'), ('930', '🏠Tehran, Iran: Office cat. B'), ('929', '🏠Hakimiyeh, Iran: Office cat. B'), ('928', '🏠Zanjan, Iran: Office cat. B'), ('927', '🏠Zahedan, Iran: Office cat. B'), ('926', '🏠Yazd, Iran: Office cat. B'), ('925', '🏠Tabriz, Iran: Office cat. B'), ('924', '🏠Shiraz, Iran: Office cat. B'), ('923', '🏠Shahroud, Iran: Office cat. B'), ('922', '🏠Shahrekord, Iran: Office cat. B'), ('921', '🏠Semnan, Iran: Office cat. B'), ('920', '🏠Sari, Iran: Office cat. B'), ('919', '🏠Sanandaj, Iran: Office cat. B'), ('918', '🏠Rasht, Iran: Office cat. B'), ('917', '🏠Qom, Iran: Office cat. B'), ('916', '🏠Urmia, Iran: Office cat. B'), ('915', '🏠Mashahd, Iran: Office cat. B'), ('914', '🏠Bandar Mahshahr, Iran: Office cat. B'), ('913', '🏠Khoy, Iran: Office cat. B'), ('912', '🏠Khoramabad, Iran: Office cat. B'), ('911', '🏠Kermanshah, Iran: Office cat. B'), ('910', '🏠Kerman, Iran: Office cat. B'), ('908', '🏠Isfahan, Iran: Office cat. B'), ('907', '🏠Hamedan, Iran: Office cat. B'), ('906', '🏠Gorgan, Iran: Office cat. B'), ('904', '🏠Qazvin, Iran: Office cat. B'), ('903', '🏠Chaloos, Iran: Office cat. B'), ('902', '🏠Bojnourd, Iran: Office cat. B'), ('901', '🏠Birjand, Iran: Office cat. B'), ('900', '🏠Bandar Abbas, Iran: Office cat. B'), ('898', '🏠Ardebil, Iran: Office cat. B'), ('897', '🏠Arak, Iran: Office cat. B'), ('896', '🏠Andimeshk, Iran: Office cat. B'), ('895', '🏠 Ahvaz, Iran: Office cat. B'), ('401', '📦🚬Mahdi Shahr, Iran: FG WH cat. A'), ('399', '📦🍂Jolfa, Iran: Leaf WH cat. B (ITC)'), ('92', '🏠Tehran, Iran: Office cat. A (HQ)'), ('28', '🏭Zanjan, Iran: Factory cat. A (JTI Parsian)')], max_length=50, null=True, verbose_name='JTI Site'),
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
