# Generated by Django 4.0.6 on 2022-08-08 11:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hs_incidents', '0002_remove_hs_incident_reporting_factory_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hs_incident',
            name='date_occured',
        ),
        migrations.RemoveField(
            model_name='hs_incident',
            name='external_authority_notification',
        ),
        migrations.RemoveField(
            model_name='hs_incident',
            name='illness',
        ),
        migrations.RemoveField(
            model_name='hs_incident',
            name='incident_description',
        ),
        migrations.RemoveField(
            model_name='hs_incident',
            name='incident_location',
        ),
        migrations.RemoveField(
            model_name='hs_incident',
            name='injury',
        ),
        migrations.RemoveField(
            model_name='hs_incident',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='hs_incident',
            name='lon',
        ),
        migrations.AddField(
            model_name='hs_incident',
            name='auth_notified',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No')], default=None, max_length=50, verbose_name='Ext. Auth. notification?'),
        ),
        migrations.AddField(
            model_name='hs_incident',
            name='date_occurred',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Occurred'),
        ),
        migrations.AddField(
            model_name='hs_incident',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(25.0), django.core.validators.MaxValueValidator(40.0)], verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='hs_incident',
            name='location',
            field=models.CharField(choices=[('Onsite', 'ON-site'), ('Offsite', 'OFF-site')], default=None, max_length=50, verbose_name='Incident Location'),
        ),
        migrations.AddField(
            model_name='hs_incident',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(44.0), django.core.validators.MaxValueValidator(64.0)], verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='illness',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='illnesses', to='hs_incidents.hs_incident', verbose_name='Incident'),
        ),
        migrations.AddField(
            model_name='injury',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='injuries', to='hs_incidents.hs_incident', verbose_name='Incident'),
        ),
        migrations.AlterField(
            model_name='hs_incident',
            name='date_created',
            field=models.DateField(blank=True, null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='hs_incident',
            name='date_reported',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Reported to Local H&S'),
        ),
        migrations.AlterField(
            model_name='hs_incident',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hs_incident',
            name='incident_classification',
            field=models.CharField(choices=[('Safety', 'Safety'), ('Health', 'Occupational Health')], default=None, max_length=50, verbose_name='Incident Classification'),
        ),
        migrations.AlterField(
            model_name='hs_incident',
            name='jti_site',
            field=models.CharField(blank=True, choices=[('1419', '🏠 Babol, Iran: Office cat. B'), ('934', '📦Zanjan, Iran: NTM WH cat. C Machinery WH'), ('933', '🏠Tehran, Iran: Office cat. B (South Tehran)'), ('932', '🏠Tehran, Iran: Office cat. B (West Tehran)'), ('931', '🏠Karaj, Iran: Office cat. B'), ('930', '🏠Tehran, Iran: Office cat. B'), ('929', '🏠Hakimiyeh, Iran: Office cat. B'), ('928', '🏠Zanjan, Iran: Office cat. B'), ('927', '🏠Zahedan, Iran: Office cat. B'), ('926', '🏠Yazd, Iran: Office cat. B'), ('925', '🏠Tabriz, Iran: Office cat. B'), ('924', '🏠Shiraz, Iran: Office cat. B'), ('923', '🏠Shahroud, Iran: Office cat. B'), ('922', '🏠Shahrekord, Iran: Office cat. B'), ('921', '🏠Semnan, Iran: Office cat. B'), ('920', '🏠Sari, Iran: Office cat. B'), ('919', '🏠Sanandaj, Iran: Office cat. B'), ('918', '🏠Rasht, Iran: Office cat. B'), ('917', '🏠Qom, Iran: Office cat. B'), ('916', '🏠Urmia, Iran: Office cat. B'), ('915', '🏠Mashahd, Iran: Office cat. B'), ('914', '🏠Bandar Mahshahr, Iran: Office cat. B'), ('913', '🏠Khoy, Iran: Office cat. B'), ('912', '🏠Khoramabad, Iran: Office cat. B'), ('911', '🏠Kermanshah, Iran: Office cat. B'), ('910', '🏠Kerman, Iran: Office cat. B'), ('908', '🏠Isfahan, Iran: Office cat. B'), ('907', '🏠Hamedan, Iran: Office cat. B'), ('906', '🏠Gorgan, Iran: Office cat. B'), ('904', '🏠Qazvin, Iran: Office cat. B'), ('903', '🏠Chaloos, Iran: Office cat. B'), ('902', '🏠Bojnourd, Iran: Office cat. B'), ('901', '🏠Birjand, Iran: Office cat. B'), ('900', '🏠Bandar Abbas, Iran: Office cat. B'), ('898', '🏠Ardebil, Iran: Office cat. B'), ('897', '🏠Arak, Iran: Office cat. B'), ('896', '🏠Andimeshk, Iran: Office cat. B'), ('895', '🏠 Ahvaz, Iran: Office cat. B'), ('401', '📦🚬Mahdi Shahr, Iran: FG WH cat. A'), ('399', '📦🍂Jolfa, Iran: Leaf WH cat. B (ITC)'), ('92', '🏠Tehran, Iran: Office cat. A (HQ)'), ('28', '🏭Zanjan, Iran: Factory cat. A (JTI Parsian)')], max_length=50, null=True, verbose_name='JTI Site'),
        ),
        migrations.AlterField(
            model_name='hs_incident',
            name='simp_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='SIMP id'),
        ),
        migrations.AlterField(
            model_name='hs_incident',
            name='work_related',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No')], default=None, max_length=50, verbose_name='Work related'),
        ),
    ]
