# Generated by Django 4.0.6 on 2022-08-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_incidents', '0003_remove_hs_incident_date_occured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='relation_to_business',
            field=models.CharField(choices=[('JTI Employee', 'JTI Employee (permanent, temporary/seasonal)'), ('Outsourced', 'Outsourced personnel /Supervised employee (JTI direct supervision)'), ('Contractor', 'Contractor'), ('Public', 'Member of public (no direct contractual relationship between JTI and injured person)')], max_length=100, verbose_name='Relation to Business'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='severity',
            field=models.CharField(choices=[('Fatality', 'Fatality'), ('LTI', '(LTI) Lost time injury'), ('RWC', '(RWC) Restricted work case'), ('MTC', '(MTC) Medical treatment case'), ('First aid', 'First aid')], max_length=100, verbose_name='Severity'),
        ),
    ]
