# Generated by Django 4.0.6 on 2022-08-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_incidents', '0005_hs_incident_user_alter_hs_incident_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
