# Generated by Django 4.0.6 on 2022-08-14 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hs_incidents', '0008_alter_injury_options_alter_hs_incident_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hs_incident',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
