# Generated by Django 4.0.6 on 2022-08-19 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hs_incidents', '0009_alter_hs_incident_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injury_or_Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_to_business', models.CharField(choices=[('JTI Employee', 'JTI Employee (permanent, temporary/seasonal)'), ('Outsourced', 'Outsourced personnel /Supervised employee (JTI direct supervision)'), ('Contractor', 'Contractor'), ('Public', 'Member of public (no direct contractual relationship between JTI and injured person)')], max_length=100, verbose_name='Relation to Business')),
                ('severity', models.CharField(choices=[('Fatality', 'Fatality'), ('LTI', '(LTI) Lost time injury'), ('RWC', '(RWC) Restricted work case'), ('MTC', '(MTC) Medical treatment case'), ('First aid', 'First aid')], max_length=100, verbose_name='Severity')),
                ('immediate_cause', models.CharField(choices=[('1', 'Exposure to physical agents (Noise, Vibration, Ionizing radiations, Heat radiation, Ultraviolet radiation, Extreme temperature, Intense light etc.)'), ('2', 'Exposure to chemical agents (Allergic provoking agents, Irritants agents from work activities such as organic solvents, ammonia, Cadmium, phosphorus, lead and their compounds….)'), ('3', 'Exposure to biological agents and infectious or parasitic diseases (Viruses, Bacteria, Fungi etc.)'), ('4', 'Long term exposure to repetitive movements or long hours in a static position'), ('5', 'Long term exposure to heavy workload'), ('6', 'Other (please specify)')], max_length=100, verbose_name='Immediate Cause - Safety')),
                ('consequence', models.CharField(choices=[('1', 'Respiratory disease (eg Green tobacco sickness, Asthma, Chronic pulmonary disease)'), ('2', 'Skin disease (eg Dermatitis, Urticaria)'), ('3', 'Musculoskeletal disorder (eg Carpal tunnel syndrome, Hernia, Back pains)'), ('4', 'Hearing loss/impairment'), ('5', 'Mental and behavioral disorder (eg Burnout, Post-traumatic stress, Anxiety)'), ('6', 'Other (please specify)')], max_length=100, verbose_name='Consequence')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=100, verbose_name='Gender')),
            ],
        ),
        migrations.RemoveField(
            model_name='injury',
            name='incident',
        ),
        migrations.AlterField(
            model_name='hs_incident',
            name='date_created',
            field=models.DateField(blank=True, null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='hs_incident',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Illness',
        ),
        migrations.DeleteModel(
            name='Injury',
        ),
        migrations.AddField(
            model_name='injury_or_illness',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='hs_incidents.hs_incident', verbose_name='Children'),
        ),
    ]
