# Generated by Django 4.0.6 on 2022-09-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_incidents', '0012_simplogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplogin',
            name='expiration',
            field=models.IntegerField(default=1, verbose_name='срок истечения'),
            preserve_default=False,
        ),
    ]
