# Generated by Django 4.0.6 on 2022-09-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_incidents', '0013_simplogin_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hs_incident',
            name='auth_notified',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=50, verbose_name='Ext. Auth. notification?'),
        ),
        migrations.AlterField(
            model_name='hs_incident',
            name='work_related',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=50, verbose_name='Work related'),
        ),
    ]
