# Generated by Django 4.0.6 on 2022-09-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs_incidents', '0014_alter_hs_incident_auth_notified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hs_incident',
            name='simp_id',
        ),
        migrations.AddField(
            model_name='hs_incident',
            name='object_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='SIMP object id'),
        ),
        migrations.AddField(
            model_name='hs_incident',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='SIMP unique id'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illnesses', to='hs_incidents.hs_incident', verbose_name='Incident'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='immediate_cause',
            field=models.CharField(choices=[('1', 'Road incident'), ('2', 'Cut by sharp object'), ('3', 'Exposure to or contact with compressed Air'), ('4', 'Exposure to fumes'), ('5', 'Exposure to or contact chemical substance'), ('6', 'Exposure to or contact with electric current'), ('7', 'Exposure to or contact with extreme temperatures'), ('8', 'Exposure to or contact with harmful substances or radiations'), ('9', 'Fall from height'), ('10', 'Fall on same level'), ('11', 'Hit by an industrial vehicle'), ('12', 'Improper body movement'), ('13', 'Injured by animal/insect'), ('14', 'Overexertion or strenuous movement'), ('15', 'Running into object'), ('16', 'Struck by falling or moving object'), ('17', 'Trapped my moving machinery or equipment')], max_length=100, verbose_name='Immediate Cause - Safety'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='hs_incidents.hs_incident', verbose_name='Incident'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='severity',
            field=models.CharField(choices=[('Fatality', 'Fatality'), ('LTI', '(LTI) Lost time injury'), ('RWC', '(RWC) Restricted work case'), ('MTC', '(MTC) Medical treatment case'), ('First aid', 'First aid')], default=('Fatality', 'Fatality'), max_length=100, verbose_name='Severity'),
        ),
    ]
