# Generated by Django 4.0.6 on 2022-09-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_incidents', '0015_remove_hs_incident_simp_id_hs_incident_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('Car', 'Car'), ('Motorcycle', 'Motorcycle'), ('Van', 'Van'), ('Rickshaw', 'Rickshaw'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='severity',
            field=models.CharField(choices=[('Fatality', 'Fatality'), ('LTI', '(LTI) Lost time injury'), ('RWC', '(RWC) Restricted work case'), ('MTC', '(MTC) Medical treatment case'), ('First aid', 'First aid')], max_length=100, verbose_name='Severity'),
        ),
    ]
